[package]
name = "arcade"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_dos = { git="https://github.com/o8vm/rust_dos.git" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
